### ISSUE TITLE
UnhandledRejection

### ISSUE THREAD

**Issue by chenboshuo** [iamcco/ds-pinyin-lsp#10]
I use conmand `:CocInstall coc-ds-pinyin-lsp` in `SpaceVim`,  and 
```
Install finished

- ✓ coc-ds-pinyin-lsp Move extension coc-ds-pinyin-lsp@0.4.0 to /home/cbs/.config/coc/extensions/node_modules/coc-ds-pinyin-lsp

```

```
[coc.nvim]: UnhandledRejection: Launching server "ds-pinyin-lsp" using command /home/cbs/.config/coc/extensions/coc-ds-pi
nyin-lsp-data/ds-pinyin-lsp failed.
Error: Launching server "ds-pinyin-lsp" using command /home/cbs/.config/coc/extensions/coc-ds-pinyin-lsp-data/ds-pinyin-l
sp failed.
    at /home/cbs/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/build/index.js:68388:37
    at async LanguageClient.createConnection (/home/cbs/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/build/index.js
:67719:28)
    at async LanguageClient._start (/home/cbs/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/build/index.js:67345:30)
```
What should I do? Thank you for your attention.

**Comment by Freed-Wu** [comment]
Can you run `/home/cbs/.config/coc/extensions/coc-ds-pinyin-lsp-data/ds-pinyin-lsp` to check if LS can work?

**Comment by Freed-Wu** [comment]
BTW I think LSP is not a specific protocol for IME, so I tend to use specific IME extension such as:

- [emacs-rime](https://github.com/DogLooksGood/emacs-rime)
- [coc-rime](https://github.com/tonyfettes/coc-rime)
- [rime.nvim](https://github.com/Freed-Wu/rime.nvim)

**Comment by chenboshuo** [comment]
> /home/cbs/.config/coc/extensions/coc-ds-pinyin-lsp-data/ds-pinyin-lsp

```
Content-Length: 75

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}%
```

Yes, but I don't know the output mesn,
Thanks you for your attention.
